a="string"
print(a[::-1])
print()
print('they said,"what\'s going on ?"')
print()
# print("they said,"what\'s going on ?"")
print("hello\npython")
print()
print("hello\\python")
print()
print("hello\'python")
print()
print("hello\tpython")
print()
str1="vishal\nvishal\tvishal"
print(str1)
print()
print(repr(str1))
print()
print(r"vishal\nvishal\tvishal")
print()
print(a.swapcase())
print(a.split())
# print(center())
# print(a.count())
print(a.replace("string","this is is a string"))
b=""
l=["vishal","vishal","vishal"]
print(b.join(l))
print(a.isupper())
print(a.islower())
print(a.isalpha())
print(a.isalnum())
print(a.isspace)
print(a.startswith("t"))
print(a.endswith("t"))
print(a.find("th"))
print(a.isdecimal())
print(min(a))
print(max(a))
print(a.isnumeric())
