tup=("hello" ,1 ,2 ,[1,2,4,4,5,6,78],3.4,(1,2,3),8,9,9,5)
print(type(tup))
# print(len(tup))
# print(tup[3][3])
# print(tup[::-1])
print(tup[0])
print(tup[-1])
print(tup[3][1])
print(tup[3:7])
print()
# for i in tup:
#     print(i,end=" ")
print(tup[::])
tup[3][0]=9 # tuple is immutable but inside the list is mutetable
print(tup)
print(("hello",)*3)
print(tup[3].count(4))
print(tup.index(9))
x=(1,2,3,4,5,[1,3],8,9,"hello",3.4)
print(tuple(enumerate(x)))
# print(max(int(x)))
print(sum((1,2,3,4,5,6,7,8)))
z=list("asdfghj")
print(tuple(z))